using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Text;
using T4TS.Example.Models;

namespace T4TS.Tests
{
    [TestClass]
    public class MemberOutputAppenderTests
    {
        [TestMethod]
        public void TypescriptVersion083YieldsBool()
        {
            var sb = new StringBuilder();
            var member = new TypeScriptInterfaceMember
            {
                Name = "Foo",
                Type = new BoolType()
            };

            var appender = new MemberOutputAppender(sb, 0, new Settings
            {
                CompatibilityVersion = new Version(0, 8, 3)
            });

            appender.AppendOutput(member);
            Assert.AreEqual("Foo: bool;", sb.ToString().Trim());
        }

        [TestMethod]
        public void TypescriptVersion090YieldsBoolean()
        {
            var sb = new StringBuilder();
            var member = new TypeScriptInterfaceMember
            {
                Name = "Foo",
                Type = new BoolType()
            };

            var appender = new MemberOutputAppender(sb, 0, new Settings
            {
                CompatibilityVersion = new Version(0, 9, 0)
            });

            appender.AppendOutput(member);
            Assert.AreEqual("Foo: boolean;", sb.ToString().Trim());
        }

        [TestMethod]
        public void DefaultTypescriptVersionYieldsBoolean()
        {
            var sb = new StringBuilder();
            var member = new TypeScriptInterfaceMember
            {
                Name = "Foo",
                Type = new BoolType()
            };

            var appender = new MemberOutputAppender(sb, 0, new Settings
            {
                CompatibilityVersion = null
            });

            appender.AppendOutput(member);
            Assert.AreEqual("Foo: boolean;", sb.ToString().Trim());
            Console.WriteLine(sb.ToString());
        }

        [TestMethod]
        public void MemberOutputAppenderTestEnumType()
        {
            var sb = new StringBuilder();

            var member = new TypeScriptInterfaceMember
            {
                Name = "Foo",
                Type = new EnumType("FooEnum")
            };

            var settings = new Settings();
            var appender = new MemberOutputAppender(sb, 0, settings);

            appender.AppendOutput(member);
            Console.WriteLine(sb.ToString());
            Assert.IsTrue(sb.ToString().Contains("FooEnum"));
        }


        [TestMethod]
        public void TestOutput()
        {
            var settings = new Settings { UseNativeDates = true };
            var res = OutputFormatter.GetOutput(GetDataToRender(settings), settings);
            Console.WriteLine(res);
            Assert.AreEqual(ExpectedResult, res);
        }


        #region - Test Data -

        [TypeScriptInterface(Module = "External1")]
        public class TestClass
        {
            public int Id { get; set; }
            public string Name { get; set; }

            public DateTime Date { get; set; }

            public List<DateTime> DatesList { get; set; }
            public DateTime[] DatesArray { get; set; }

            public WeakReference RefObject { get; set; }

            public int[] IntArray { get; set; }

            public TestClass[] SelfArray { get; set; }

            public bool IsVisible { get; set; }
            public bool? IsOptional { get; set; }
            public int? IntOptional { get; set; }

            public TestClass Self { get; set; }
            public TestEnum EnumProp { get; set; }
            public TestEnum? EnumPropNull { get; set; }

            public TestEnum[] EnumArray { get; set; }
        }

        [TypeScriptEnum(Module = "External2")]
        public enum TestEnum
        {
            [TypeScriptMember(Name = "TheItem1")]
            Item1 = 1,
            Item2 = 2,
            Item21,
            Item22,
            Item23,
            Item3 = 5,
            Item4,
        }

        const string ExpectedResult = @"/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module External1 {
    /** Generated from T4TS.Tests.MemberOutputAppenderTests+TestClass **/
    export interface TestClass {
        Id: number;
        Name: string;
        Date: Date;
        DatesList: Date[];
        DatesArray: Date[];
        RefObject: any;
        IntArray: number[];
        SelfArray: External1.TestClass[];
        IsVisible: boolean;
        IsOptional: boolean;
        IntOptional: number;
        Self: External1.TestClass;
        EnumProp: External2.TestEnum;
        EnumPropNull: External2.TestEnum;
        EnumArray: External2.TestEnum[];
    }
}

declare module External2 {
    /** Generated from T4TS.Tests.MemberOutputAppenderTests+TestEnum **/
    enum TestEnum {
        TheItem1 = 1,
        Item2 = 2,
        Item21 = 3,
        Item22 = 4,
        Item23 = 5,
        Item3 = 5,
        Item4 = 6,
    }
}
";
        List<TypeScriptModule> GetDataToRender(Settings settings)
        {
            var generator = new CodeTraverser(
                new MockSolution(

                    typeof(TestClass),
                    typeof(TestEnum)

                    ).Object, settings);
            return generator.GetAllInterfaces().ToList();
        }


        #endregion

    }
}
